package io.smithycpp.codegen;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;
import software.amazon.smithy.build.MockManifest;
import software.amazon.smithy.build.PluginContext;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.node.Node;
import software.amazon.smithy.model.node.ObjectNode;

/**
 * The generated BUILD.bazel is the one artifact issue #48 flagged as pinned by goldens alone: the
 * protocol conformance suites never load it. These tests assert the target set per mode and the
 * knobs that control emission.
 */
class BuildFileGeneratorTest {

  private static final String MODEL =
      """
      $version: "2.0"
      namespace test.build
      use smithy.cpp.protocols#jsonRpc2

      @jsonRpc2
      service Svc { version: "1", operations: [Op] }
      operation Op { input := { name: String } }
      """;

  private static MockManifest generate(ObjectNode settings) {
    return generate(MODEL, settings);
  }

  private static MockManifest generate(String modelText, ObjectNode settings) {
    Model model =
        Model.assembler()
            .discoverModels(BuildFileGeneratorTest.class.getClassLoader())
            .addUnparsedModel("build-test.smithy", modelText)
            .assemble()
            .unwrap();
    MockManifest manifest = new MockManifest();
    PluginContext context =
        PluginContext.builder().fileManifest(manifest).model(model).settings(settings).build();
    new CppCodegenPlugin().execute(context);
    return manifest;
  }

  private static ObjectNode settings(String mode) {
    return Node.objectNodeBuilder()
        .withMember("service", "test.build#Svc")
        .withMember("namespace", "test::build")
        .withMember("runtimeTarget", "//runtime:core")
        .withMember("mode", mode)
        .build();
  }

  @Test
  void bothModeEmitsTypesSerdeClientAndServerTargets() {
    String build = generate(settings("both")).expectFileString("/BUILD.bazel");
    assertTrue(build.contains("name = \"types\""), build);
    assertTrue(build.contains("name = \"serde\""), build);
    assertTrue(build.contains("name = \"client\""), build);
    assertTrue(build.contains("name = \"server\""), build);
    assertTrue(build.contains("# Code generated by smithy-cpp (cpp-codegen). DO NOT EDIT."));
    assertTrue(build.contains("load(\"@rules_cc//cc:defs.bzl\", \"cc_library\")"), build);
  }

  @Test
  void clientModeOmitsTheServerTarget() {
    String build = generate(settings("client")).expectFileString("/BUILD.bazel");
    assertTrue(build.contains("name = \"client\""), build);
    assertFalse(build.contains("name = \"server\""), build);
  }

  @Test
  void typesModeEmitsOnlyTheTypesTarget() {
    String build = generate(settings("types")).expectFileString("/BUILD.bazel");
    assertTrue(build.contains("name = \"types\""), build);
    assertFalse(build.contains("name = \"client\""), build);
    assertFalse(build.contains("name = \"server\""), build);
  }

  @Test
  void runtimeDepsPointAtTheConfiguredTarget() {
    String build = generate(settings("both")).expectFileString("/BUILD.bazel");
    assertTrue(build.contains("\"//runtime:core\""), build);
    // The consumer default is the external-repo spelling.
    String external =
        generate(
                Node.objectNodeBuilder()
                    .withMember("service", "test.build#Svc")
                    .withMember("namespace", "test::build")
                    .build())
            .expectFileString("/BUILD.bazel");
    assertTrue(external.contains("\"@smithy_cpp//runtime:core\""), external);
  }

  @Test
  void emitBuildFileFalseSuppressesTheFile() {
    ObjectNode settings =
        Node.objectNodeBuilder()
            .withMember("service", "test.build#Svc")
            .withMember("namespace", "test::build")
            .withMember("emitBuildFile", false)
            .build();
    MockManifest manifest = generate(settings);
    assertFalse(manifest.hasFile("/BUILD.bazel"), "emitBuildFile=false must suppress BUILD");
    assertTrue(manifest.hasFile("/include/test/build/types.h"));
  }

  @Test
  void gzipCompressionLinksTheCompressionTarget() {
    // The BUILD dep keys on ProtocolSupport.gzipCompressed, not on
    // @requestCompression's mere presence. The negative direction is
    // untestable through a real model — Smithy's RequestCompressionTrait
    // validator rejects every encoding except gzip at assembly — so the
    // predicate's non-gzip arm is pinned by ProtocolSupportTest instead.
    String compressed =
        """
        $version: "2.0"
        namespace test.build
        use smithy.cpp.protocols#jsonRpc2

        @jsonRpc2
        service Svc { version: "1", operations: [Op] }

        @requestCompression(encodings: ["gzip"])
        operation Op { input := { data: String } }
        """;
    String build = generate(compressed, settings("both")).expectFileString("/BUILD.bazel");
    assertTrue(build.contains(":compression"), build);
    // And the base model (no compression anywhere) must not link it.
    String plain = generate(settings("both")).expectFileString("/BUILD.bazel");
    assertFalse(plain.contains(":compression"), plain);
  }
}
