package io.smithycpp.codegen;

/** Emits the Bazel BUILD file for a generated module (buildifier-clean). */
final class BuildFileGenerator {

  private BuildFileGenerator() {}

  static void run(CppContext context) {
    CppSettings settings = context.settings();
    String content =
        """
        # Code generated by smithy-cpp (cpp-codegen). DO NOT EDIT.

        load("@rules_cc//cc:defs.bzl", "cc_library")

        package(default_visibility = ["//visibility:public"])

        cc_library(
            name = "types",
            hdrs = ["%s"],
            includes = ["include"],
            deps = ["%s"],
        )
        """
            .formatted(settings.typesHeaderFile(), settings.runtimeTarget());
    context.fileManifest().writeFile("BUILD.bazel", content);
  }
}
