package io.smithycpp.codegen;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/** Emits the Bazel BUILD file for a generated module (buildifier-clean). */
final class BuildFileGenerator {

  private BuildFileGenerator() {}

  static void run(
      CppContext context,
      ProtocolGenerator protocol,
      boolean hasClient,
      boolean hasSerde,
      boolean hasServer,
      boolean hasCompression) {
    CppSettings settings = context.settings();
    StringBuilder out = new StringBuilder();
    out.append(
        """
        # Code generated by smithy-cpp (cpp-codegen). DO NOT EDIT.

        load("@rules_cc//cc:defs.bzl", "cc_library")

        package(default_visibility = ["//visibility:public"])

        cc_library(
            name = "types",
            hdrs = ["%s"],
            includes = ["include"],
            deps = ["%s"],
        )
        """
            .formatted(settings.typesHeaderFile(), settings.runtimeTarget()));

    String pkg = settings.runtimePackage();
    if (hasSerde) {
      out.append(
          """

          cc_library(
              name = "serde",
              srcs = ["src/serde.cc"],
              hdrs = ["%s"],
              includes = ["include"],
              deps = [
                  ":types",
                  "%s:core",
              ],
          )
          """
              .formatted(settings.serdeHeaderFile(), pkg));
    }
    if (hasClient) {
      List<String> deps = new ArrayList<>();
      deps.add("\":serde\"");
      deps.add("\":types\"");
      deps.add("\"" + pkg + ":client\"");
      deps.add("\"" + pkg + ":core\"");
      deps.add("\"" + pkg + ":http\"");
      if (hasCompression) {
        deps.add("\"" + pkg + ":compression\"");
      }
      for (String dep : protocol.runtimeDeps()) {
        deps.add("\"" + pkg + dep + "\"");
      }
      sortLabels(deps);
      out.append(
          """

          cc_library(
              name = "client",
              srcs = ["src/client.cc"],
              hdrs = ["%s"],
              includes = ["include"],
              deps = [
          """
              .formatted(settings.clientHeaderFile()));
      appendDeps(out, deps);
    }
    if (hasServer) {
      List<String> serverDeps = new ArrayList<>();
      serverDeps.add("\":serde\"");
      serverDeps.add("\":types\"");
      serverDeps.add("\"" + pkg + ":core\"");
      serverDeps.add("\"" + pkg + ":http\"");
      serverDeps.add("\"" + pkg + ":server\"");
      if (hasCompression) {
        serverDeps.add("\"" + pkg + ":compression\"");
      }
      for (String dep : protocol.runtimeDeps()) {
        serverDeps.add("\"" + pkg + dep + "\"");
      }
      sortLabels(serverDeps);
      out.append(
          """

          cc_library(
              name = "server",
              srcs = ["src/server.cc"],
              hdrs = ["%s"],
              includes = ["include"],
              deps = [
          """
              .formatted(settings.serverHeaderFile()));
      appendDeps(out, serverDeps);
    }
    context.fileManifest().writeFile("BUILD.bazel", out.toString());
  }

  /**
   * Buildifier's label ordering: same-package (":x") labels sort before absolute ("//pkg:x") ones,
   * lexicographic within each group.
   */
  private static void sortLabels(List<String> deps) {
    deps.sort(
        Comparator.comparing((String d) -> !d.startsWith("\":"))
            .thenComparing(Comparator.naturalOrder()));
  }

  private static void appendDeps(StringBuilder out, List<String> deps) {
    for (String dep : deps) {
      out.append("        ").append(dep).append(",\n");
    }
    out.append("    ],\n)\n");
  }
}
