package io.smithycpp.codegen;

import java.util.ArrayList;
import java.util.List;

/** Emits the Bazel BUILD file for a generated module (buildifier-clean). */
final class BuildFileGenerator {

  private BuildFileGenerator() {}

  static void run(
      CppContext context, ProtocolGenerator protocol, boolean hasClient, boolean hasSerde) {
    CppSettings settings = context.settings();
    StringBuilder out = new StringBuilder();
    out.append(
        """
        # Code generated by smithy-cpp (cpp-codegen). DO NOT EDIT.

        load("@rules_cc//cc:defs.bzl", "cc_library")

        package(default_visibility = ["//visibility:public"])

        cc_library(
            name = "types",
            hdrs = ["%s"],
            includes = ["include"],
            deps = ["%s"],
        )
        """
            .formatted(settings.typesHeaderFile(), settings.runtimeTarget()));

    String pkg = settings.runtimePackage();
    if (hasClient) {
      List<String> deps = new ArrayList<>();
      deps.add("\":types\"");
      deps.add("\"" + pkg + ":client\"");
      deps.add("\"" + pkg + ":core\"");
      deps.add("\"" + pkg + ":http\"");
      for (String dep : protocol.runtimeDeps()) {
        deps.add("\"" + pkg + dep + "\"");
      }
      // Match buildifier's label ordering: same-package (":x") labels sort
      // before absolute ("//pkg:x") ones, lexicographic within each group.
      deps.sort(
          java.util.Comparator.comparing((String d) -> !d.startsWith("\":"))
              .thenComparing(java.util.Comparator.naturalOrder()));
      out.append(
          """

          cc_library(
              name = "client",
              srcs = [
                  "src/client.cc",
                  "src/serde.cc",
              ],
              hdrs = [
                  "%s",
                  "%s",
              ],
              includes = ["include"],
              deps = [
          """
              .formatted(settings.clientHeaderFile(), settings.serdeHeaderFile()));
      for (String dep : deps) {
        out.append("        ").append(dep).append(",\n");
      }
      out.append("    ],\n)\n");
    } else if (hasSerde) {
      out.append(
          """

          cc_library(
              name = "serde",
              srcs = ["src/serde.cc"],
              hdrs = ["%s"],
              includes = ["include"],
              deps = [
                  ":types",
                  "%s:core",
              ],
          )
          """
              .formatted(settings.serdeHeaderFile(), pkg));
    }
    context.fileManifest().writeFile("BUILD.bazel", out.toString());
  }
}
