package io.smithycpp.codegen;

import java.util.Set;
import java.util.TreeSet;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolWriter;

/**
 * Writer for one generated C++ file. Collects {@code #include}s while the body is written, renders
 * them sorted (angle includes first, then quoted) after the file header, and wraps the body in the
 * module's namespace. Output is byte deterministic.
 */
public final class CppWriter extends SymbolWriter<CppWriter, CppWriter.IncludeContainer> {

  private final String filename;
  private final String cppNamespace;

  public CppWriter(String filename, String cppNamespace) {
    super(new IncludeContainer());
    this.filename = filename;
    this.cppNamespace = cppNamespace;
    trimTrailingSpaces();
    setIndentText("  ");
  }

  /** Factory used by the writer delegator. */
  public static final class Factory implements SymbolWriter.Factory<CppWriter> {
    private final CppSettings settings;

    public Factory(CppSettings settings) {
      this.settings = settings;
    }

    @Override
    public CppWriter apply(String filename, String namespace) {
      return new CppWriter(filename, settings.namespace());
    }
  }

  /** Records an include in angle ({@code <vector>}) or quote ({@code "smithy/x.h"}) form. */
  public CppWriter addInclude(String include) {
    getImportContainer().add(include);
    return this;
  }

  /** Records every header a symbol needs. */
  public CppWriter addIncludesFor(Symbol symbol) {
    CppSymbolProvider.headersOf(symbol).forEach(this::addInclude);
    return this;
  }

  private boolean isCppSource() {
    return filename.endsWith(".h") || filename.endsWith(".cc");
  }

  @Override
  public String toString() {
    if (!isCppSource()) {
      return super.toString();
    }
    StringBuilder out = new StringBuilder();
    out.append("// Code generated by smithy-cpp (cpp-codegen). DO NOT EDIT.\n\n");
    if (filename.endsWith(".h")) {
      out.append("#pragma once\n\n");
    }
    String includes = getImportContainer().render(filename);
    if (!includes.isEmpty()) {
      out.append(includes).append('\n');
    }
    out.append("namespace ").append(cppNamespace).append(" {\n\n");
    String body = super.toString();
    out.append(body);
    if (!body.endsWith("\n")) {
      out.append('\n');
    }
    out.append("}  // namespace ").append(cppNamespace).append('\n');
    return out.toString();
  }

  /** Include set with deterministic rendering. */
  public static final class IncludeContainer
      implements software.amazon.smithy.codegen.core.ImportContainer {

    private final Set<String> angle = new TreeSet<>();
    private final Set<String> quoted = new TreeSet<>();

    void add(String include) {
      if (include.startsWith("<")) {
        angle.add(include);
      } else {
        quoted.add(include);
      }
    }

    String render(String filename) {
      StringBuilder out = new StringBuilder();
      for (String include : angle) {
        out.append("#include ").append(include).append('\n');
      }
      boolean wroteQuoted = false;
      for (String include : quoted) {
        // The file being generated never includes itself.
        if (filename.endsWith(include.replace("\"", ""))) {
          continue;
        }
        if (!wroteQuoted && !angle.isEmpty()) {
          out.append('\n');
        }
        wroteQuoted = true;
        out.append("#include ").append(include).append('\n');
      }
      return out.toString();
    }

    @Override
    public void importSymbol(Symbol symbol, String alias) {
      CppSymbolProvider.headersOf(symbol).forEach(this::add);
    }
  }
}
