package io.smithycpp.codegen;

/** Emits tests/BUILD.bazel for a generated module (buildifier-clean). */
final class TestsBuildFileGenerator {

  private TestsBuildFileGenerator() {}

  static void run(CppContext context, boolean hasProtocolTests) {
    String module = context.settings().testsPackage();
    String runtime = context.settings().runtimePackage();
    StringBuilder out = new StringBuilder();
    out.append(
        """
        # Code generated by smithy-cpp (cpp-codegen). DO NOT EDIT.

        load("@rules_cc//cc:defs.bzl", "cc_test")

        cc_test(
            name = "smoke_test",
            size = "small",
            srcs = ["smoke_test.cc"],
            deps = [
                "%s:client",
                "%s:server",
                "%s:client",
                "%s:http",
                "@googletest//:gtest_main",
            ],
        )
        """
            .formatted(module, module, runtime, runtime));
    if (hasProtocolTests) {
      for (String kind : new String[] {"request", "response"}) {
        out.append(
            """

            cc_test(
                name = "%s_tests",
                size = "small",
                srcs = ["%s_tests.cc"],
                deps = [
                    "%s:client",
                    "%s:protocol_test_support",
                    "@googletest//:gtest_main",
                ],
            )
            """
                .formatted(kind, kind, module, runtime));
      }
    }
    context.fileManifest().writeFile("tests/BUILD.bazel", out.toString());
  }
}
